export const ActionTypes = {
    DELETE_ARC: 'DELETE_ARC',
    NEW_ARC: 'NEW_ARC',
    EDIT_ARC: 'EDIT_ARC',
    EDIT_ARC_ACTIVE:"EDIT_ARC_ACTIVE",

    GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
    GET_ARC_REQUEST:"GET_ARC_REQUEST",
    GET_SEARCHED_DATA:"GET_SEARCHED_DATA",

    ERROR_HANDLING_ADD_ARC: "ERROR_HANDLING_ADD_ARC",
    ANY_ERROR: "ANY_ERROR",

    SEARCHED_VALUE: "SEARCHED_VALUE",

    LOGIN_NAME:"LOGIN_NAME",
    IS_LOG_IN: "IS_LOG_IN"
}

