export const ActionTypes = {
    SET_ARC: 'SET_ARC',
    DELETE_ARC: 'DELETE_ARC',
    NEW_ARC: 'NEW_ARC',
    EDIT_ARC: 'EDIT_ARC',
    EDIT_ARC_ACTIVE:"EDIT_ARC_ACTIVE",

    GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
    GET_ARC_REQUEST:"GET_ARC_REQUEST",
    GET_SEARCHED_DATA:"GET_SEARCHED_DATA"


}

