const data = [
  {
    id: 26007,
    keY_NAME: 'Atakan10',
    keY_VALUE: 'Emre',
    keY_COMMENT: 'Value1',
    keY_VALUE_EN: 'Value1',
    keY_VALUE_RU: 'Value1',
    keY_VALUE_RO: 'Value1',
    keY_VALUE_TR: 'Value1',
    keY_VALUE_DE: 'Value1',
    isActive: true,
    createDate: '2021-08-03T14:21:09.2390736+03:00',
    createUser: 'admin',
    createrApp: 'app',
    creatorAppVersion: 'v1',
    updateDate: '0001-01-01T00:00:00+00:00',
    updaterUser: 'Emre',
    updaterApp: null,
    updaterAppVersion: null,
  },
  {
    id: 1003,
    keY_NAME: 'Atakan2',
    keY_VALUE: 'Value2',
    keY_COMMENT: 'KeyComment22',
    keY_VALUE_EN: 'KEY_VALUE_EN2',
    keY_VALUE_RU: 'KEY_VALUE_RU2',
    keY_VALUE_RO: 'KEY_VALUE_RO2',
    keY_VALUE_TR: 'KEY_VALUE_TR2',
    keY_VALUE_DE: 'KEY_VALUE_DE2',
    isActive: true,
    createDate: '2021-01-01T00:00:00+00:00',
    createUser: 'Atakan2',
    createrApp: 'Atakan2',
    creatorAppVersion: 'Atakan2',
    updateDate: '2021-01-01T00:00:00+00:00',
    updaterUser: 'Atakan',
    updaterApp: 'Atakan2',
    updaterAppVersion: 'Atakan2',
  },
  {
    id: 1008,
    keY_NAME: 'Atakan3',
    keY_VALUE: 'Emre',
    keY_COMMENT: 'KeyComment1',
    keY_VALUE_EN: 'KEY_VALUE_EN1',
    keY_VALUE_RU: 'KEY_VALUE_RU2',
    keY_VALUE_RO: 'KEY_VALUE_RO1',
    keY_VALUE_TR: 'KEY_VALUE_TR1',
    keY_VALUE_DE: 'KEY_VALUE_DE1',
    isActive: true,
    createDate: '2021-01-01T00:00:00+00:00',
    createUser: 'Ataka1n',
    createrApp: 'Atakan1',
    creatorAppVersion: 'Atakan1',
    updateDate: '2021-01-01T00:00:00+00:00',
    updaterUser: 'Atakan',
    updaterApp: 'Atakan1',
    updaterAppVersion: 'Atakan1',
  },
  {
    id: 1009,
    keY_NAME: 'Atakan4',
    keY_VALUE: 'Value2',
    keY_COMMENT: 'KeyComment2',
    keY_VALUE_EN: 'KEY_VALUE_EN2',
    keY_VALUE_RU: 'KEY_VALUE_RU2',
    keY_VALUE_RO: 'KEY_VALUE_RO2',
    keY_VALUE_TR: 'KEY_VALUE_TR2',
    keY_VALUE_DE: 'KEY_VALUE_DE2',
    isActive: true,
    createDate: '2021-01-01T00:00:00+00:00',
    createUser: 'Atakan2',
    createrApp: 'Atakan2',
    creatorAppVersion: 'Atakan2',
    updateDate: '2021-01-01T00:00:00+00:00',
    updaterUser: 'Atakan2',
    updaterApp: 'Atakan2',
    updaterAppVersion: 'Atakan2',
  },
  {
    id: 1010,
    keY_NAME: 'Atakan5',
    keY_VALUE: 'Value1',
    keY_COMMENT: 'KeyComment555',
    keY_VALUE_EN: 'KEY_VALUE_EN1',
    keY_VALUE_RU: 'KEY_VALUE_RU1',
    keY_VALUE_RO: 'KEY_VALUE_RO1',
    keY_VALUE_TR: 'KEY_VALUE_TR1',
    keY_VALUE_DE: 'KEY_VALUE_DE1',
    isActive: true,
    createDate: '2021-01-01T00:00:00+00:00',
    createUser: 'Ataka1n',
    createrApp: 'Atakan1',
    creatorAppVersion: 'Atakan1',
    updateDate: '2021-01-01T00:00:00+00:00',
    updaterUser: 'Atakan',
    updaterApp: 'Atakan1',
    updaterAppVersion: 'Atakan1',
  },
  {
    id: 1011,
    keY_NAME: 'Atakan6',
    keY_VALUE: 'Value222',
    keY_COMMENT: 'KeyComment262626',
    keY_VALUE_EN: 'KEY_VALUE_EN2',
    keY_VALUE_RU: 'KEY_VALUE_RU222',
    keY_VALUE_RO: 'KEY_VALUE_RO2',
    keY_VALUE_TR: 'KEY_VALUE_TR2',
    keY_VALUE_DE: 'KEY_VALUE_DE2',
    isActive: true,
    createDate: '2021-01-01T00:00:00+00:00',
    createUser: 'Atakan2',
    createrApp: 'Atakan2',
    creatorAppVersion: 'Atakan2',
    updateDate: '2021-01-01T00:00:00+00:00',
    updaterUser: 'Atakan',
    updaterApp: 'Atakan2',
    updaterAppVersion: 'Atakan2',
  },
  {
    id: 1012,
    keY_NAME: 'Atakan7',
    keY_VALUE: 'Value1',
    keY_COMMENT: 'KeyComment1',
    keY_VALUE_EN: 'KEY_VALUE_EN1',
    keY_VALUE_RU: 'KEY_VALUE_RU1',
    keY_VALUE_RO: 'KEY_VALUE_RO1',
    keY_VALUE_TR: 'KEY_VALUE_TR1',
    keY_VALUE_DE: 'KEY_VALUE_DE1',
    isActive: true,
    createDate: '2021-01-01T00:00:00+00:00',
    createUser: 'Ataka1n',
    createrApp: 'Atakan1',
    creatorAppVersion: 'Atakan1',
    updateDate: '2021-01-01T00:00:00+00:00',
    updaterUser: 'Atakan1',
    updaterApp: 'Atakan1',
    updaterAppVersion: 'Atakan1',
  },
  {
    id: 1013,
    keY_NAME: 'Atakan8',
    keY_VALUE: 'Value2',
    keY_COMMENT: 'KeyComment2',
    keY_VALUE_EN: 'KEY_VALUE_EN2',
    keY_VALUE_RU: 'KEY_VALUE_RU2',
    keY_VALUE_RO: 'KEY_VALUE_RO2',
    keY_VALUE_TR: 'KEY_VALUE_TR2',
    keY_VALUE_DE: 'KEY_VALUE_DE2',
    isActive: true,
    createDate: '2021-01-01T00:00:00+00:00',
    createUser: 'Atakan2',
    createrApp: 'Atakan2',
    creatorAppVersion: 'Atakan2',
    updateDate: '2021-01-01T00:00:00+00:00',
    updaterUser: 'Atakan2',
    updaterApp: 'Atakan2',
    updaterAppVersion: 'Atakan2',
  },
  {
    id: 1014,
    keY_NAME: 'Atakan9',
    keY_VALUE: 'Value1',
    keY_COMMENT: 'KeyComment1',
    keY_VALUE_EN: 'KEY_VALUE_EN1',
    keY_VALUE_RU: 'KEY_VALUE_RU1',
    keY_VALUE_RO: 'KEY_VALUE_RO1',
    keY_VALUE_TR: 'KEY_VALUE_TR1',
    keY_VALUE_DE: 'KEY_VALUE_DE1',
    isActive: true,
    createDate: '2021-01-01T00:00:00+00:00',
    createUser: 'Ataka1n',
    createrApp: 'Atakan1',
    creatorAppVersion: 'Atakan1',
    updateDate: '2021-01-01T00:00:00+00:00',
    updaterUser: 'Atakan1',
    updaterApp: 'Atakan1',
    updaterAppVersion: 'Atakan1',
  },
  {
    id: 16014,
    keY_NAME: 'msg 13 Ask Confirm Delete Return Box',
    keY_VALUE: 'value',
    keY_COMMENT: 'valueComment',
    keY_VALUE_EN:
      'Are you sure you want To Delete  the {0} item Read for  Goods Receive Order  After ITS Confirmation ?',
    keY_VALUE_RU:
      'Вы уверены, что хотите удалить данные {0}, считанный для заказа на получение товаров, после подтверждения ITS?',
    keY_VALUE_RO: 'ro',
    keY_VALUE_TR: null,
    keY_VALUE_DE: null,
    isActive: true,
    createDate: '2021-08-03T14:21:09.2390736+03:00',
    createUser: 'admin',
    createrApp: 'app',
    creatorAppVersion: 'v1',
    updateDate: '0001-01-01T00:00:00+00:00',
    updaterUser: 'Atakan1',
    updaterApp: null,
    updaterAppVersion: null,
  },
];

export default data;
